pipeline_name: dummy-predictor-training
experiment_name: dummy-predictor-exp
pipeline_schedule: "1 * * * *"
timezone: "Europe/Berlin"

labels:
  team: team_name

parameters:
  model_name: tx.fraud_detector
  model_parameters:
    max_iterations: 20
